# Generated by Django 3.1a1 on 2020-06-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20200614_1853'),
        ('users', '0003_profile_email_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.apartment'),
        ),
    ]
