# Generated by Django 3.1b1 on 2020-06-27 20:17

from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, default=invoices.models.increment_invoice_number, max_length=500, null=True)),
                ('invoice_no', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
