# Generated by Django 3.1b1 on 2020-06-27 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildings', '0005_auto_20200626_1618'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_due',
            field=models.DateField(default=invoices.models.get_due_date),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_received',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='related_apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.apartment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
