# Generated by Django 3.1b1 on 2020-06-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200627_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_received',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_water', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cold_water', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('sewage', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('electricity', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('gas', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('repair_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice')),
            ],
        ),
    ]
