# Generated by Django 3.1b1 on 2020-06-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20200630_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.IntegerField(choices=[(1, 'Awaiting confirmation'), (2, 'Awaiting payment'), (3, 'Finished'), (4, 'Payment failed')], default=1),
        ),
    ]
