# Generated by Django 3.1b1 on 2020-07-02 21:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20200630_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='cold_water',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='electricity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='gas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='hot_water',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='repair_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='sewage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
