# Generated by Django 3.1b1 on 2020-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20200614_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='area',
            field=models.FloatField(default=40.0),
        ),
        migrations.AddField(
            model_name='building',
            name='service_charge',
            field=models.FloatField(choices=[(3.62, 'Insulated'), (3.33, 'Non-Insulated')], default=3.62),
        ),
    ]
