# Generated by Django 3.1b1 on 2020-06-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_auto_20200629_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultServiceUsagePP',
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
    ]
